# Primer parcial - en desarrollo
16/09/2026

[Dataset](https://www.kaggle.com/datasets/nudratabbas/top-50-universities-in-the-u-s-forbes-2026/data?select=US_Top_50_Universities_2026.csv)

# Unidad 1: Fundamentos de Py

In [1]:
import numpy as np

In [2]:
# CRear una lista de diccionarios con los siguientes datos
unis = [
    {"nombre": "Stanford", "ranking": 4, "emp_ratio": 97.8},
    {"nombre": "MIT", "ranking": 1, "emp_ratio": 96.2},
    {"nombre": "Yale", "ranking": 9, "emp_ratio": 93.3},
]

In [3]:
def mostrar_unis(unis, n):
    n_unis = unis[:n]
    for u in n_unis:
        print(u)

mostrar_unis(unis, 5)

{'nombre': 'Stanford', 'ranking': 4, 'emp_ratio': 97.8}
{'nombre': 'MIT', 'ranking': 1, 'emp_ratio': 96.2}
{'nombre': 'Yale', 'ranking': 9, 'emp_ratio': 93.3}

In [4]:
def mostrar_unis(unis, cant_reg=None):
    if cant_reg and cant_reg <= len(unis):
        selected_unis = unis[:cant_reg]
    else:
        selected_unis = unis
    for u in selected_unis:
        print(u)

mostrar_unis(unis, 6)

{'nombre': 'Stanford', 'ranking': 4, 'emp_ratio': 97.8}
{'nombre': 'MIT', 'ranking': 1, 'emp_ratio': 96.2}
{'nombre': 'Yale', 'ranking': 9, 'emp_ratio': 93.3}

In [5]:
# Calificar universidades
def calificar_unis(unis):
    for u in unis:
        if 1 <= u["ranking"] <=5:
            u["nivel"] = "Top5"
        elif 5 < u["ranking"] <=10:
            u["nivel"] = "Top10"
        else:
            u["nivel"] = "Top50"

calificar_unis(unis)
mostrar_unis(unis, 6)

{'nombre': 'Stanford', 'ranking': 4, 'emp_ratio': 97.8, 'nivel': 'Top5'}
{'nombre': 'MIT', 'ranking': 1, 'emp_ratio': 96.2, 'nivel': 'Top5'}
{'nombre': 'Yale', 'ranking': 9, 'emp_ratio': 93.3, 'nivel': 'Top10'}

In [6]:
# Generar una funcion que retorne el diccionario de la universidad con mayor ranking
def buscar_mejor_emp_ratio(unis):
    mayor_emp_rate = unis[0]
    for u in unis:
        if u["emp_ratio"] > mayor_emp_rate["emp_ratio"]:
            mayor_emp_rate = u
    return mayor_emp_rate

print(buscar_mejor_emp_ratio(unis))

{'nombre': 'Stanford', 'ranking': 4, 'emp_ratio': 97.8, 'nivel': 'Top5'}

In [7]:
def calcular_emp_ratio_avg(unis):
    emp_list = [u["emp_ratio"] for u in unis]
    emp_ratio_avg = sum(emp_list) / len(emp_list)
    return emp_ratio_avg

print(calcular_emp_ratio_avg(unis))

95.76666666666667

In [8]:
def uni_mejor_emp_ratio(unis):
    try:
        calificar_unis(unis)
        uni_mr = buscar_mejor_emp_ratio(unis)
        er_avg = calcular_emp_ratio_avg(unis)
        print(
            f"La Universidad con mayor ratio de empleabilidad es {uni_mr["nombre"]} que se encuentra en el {uni_mr["nivel"]} con un índice de empleabilidad de {uni_mr["emp_ratio"]} % sobre un promedio de {er_avg}"
        )
    except Exception as e:
        print(f"ERROR: {e}")

In [9]:
uni_mejor_emp_ratio(unis)

La Universidad con mayor ratio de empleabilidad es Stanford que se encuentra en el Top5 con un índice de empleabilidad de 97.8 % sobre un promedio de 95.76666666666667

# Unidad 2: NumPy, Pandas, IDE

In [10]:
def cal_est_emp_unis(unis):
    emp_list = [u["emp_ratio"] for u in unis]
    emp_array = np.array(emp_list)
    count = len(emp_array)
    max = np.max(emp_array)
    min = np.min(emp_array)
    mean = np.mean(emp_array)
    median = np.median(emp_array)
    std = np.std(emp_array)

    print(f"Cantidad: {count}\nMáximo: {max}\nMínimo: {min}\nMedia: {mean:.2f}\nMediana: {median:.2f}\nDesvío: {std:.2f}")

cal_est_emp_unis(unis)

Cantidad: 3
Máximo: 97.8
Mínimo: 93.3
Media: 95.77
Mediana: 96.20
Desvío: 1.86

# Unidad 3: EDA, Data quality & Transformaciones

## 1. Importar libreriías

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## 2. Cargar dataset

In [12]:
# Cargar el dataset localmente
df = pd.read_csv("US_Top_50_Universities_2026.csv")

print(f"Dataset cargado: {df.shape[0]:,} filas × {df.shape[1]} columnas")
df.shape

Dataset cargado: 50 filas × 8 columnas

(50, 8)

## Rompemos el dataframe

In [13]:
# Generar 3 registros duplicados
df_duplicados = df.sample(3)
df = pd.concat([df, df_duplicados])

In [14]:
# Reemplazamos . por , en Employment_Rate
df["Employment_Rate"] = df["Employment_Rate"].astype(str)
df["Employment_Rate"] = df["Employment_Rate"].str.replace(".", ",", regex=False)

In [15]:
# Generar 5 valores nulos
import numpy as np

indices = df.sample(1).index
df.loc[indices, "Employment_Rate"] = np.nan
indices = df.sample(5).index
df.loc[indices, "Intl_Student_Ratio"] = np.nan

## 3. EDA

In [16]:
df.head()

,University_Name,National_Rank,Founded_Year,Institution_Type,State,Research_Impact_Score,Intl_Student_Ratio,Employment_Rate
0,Massachusetts Institute of Technology (MIT),1,1861,Private,MA,100.0,91.6,"96,2"
1,Columbia University,2,1754,Private,NY,95.9,83.7,"92,1"
2,Princeton University,3,1746,Private,NJ,99.0,70.0,"94,5"
3,Stanford University,4,1891,Private,CA,99.5,73.5,"97,8"
4,"University of California, Berkeley",5,1868,Public,CA,98.9,70.6,"91,4"

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 43
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   University_Name        53 non-null     object
 1   National_Rank          53 non-null     int64
 2   Founded_Year           53 non-null     int64
 3   Institution_Type       53 non-null     object
 4   State                  53 non-null     object
 5   Research_Impact_Score  53 non-null     float64
 6   Intl_Student_Ratio     47 non-null     float64
 7   Employment_Rate        52 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 5.8+ KB

In [18]:
# Normalizamos nombres de columnas
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_", regex=False)
)

In [19]:
df.describe()

       national_rank  founded_year  research_impact_score  intl_student_ratio
count      53.000000     53.000000              53.000000           47.000000
mean       25.830189   1845.283019              80.490566           44.131915
std        14.804802     64.406276              23.387803           31.329290
min         1.000000   1636.000000              28.500000            4.200000
25%        13.000000   1817.000000              82.100000           15.000000
50%        26.000000   1861.000000              89.200000           25.400000
75%        39.000000   1887.000000              96.300000           73.800000
max        50.000000   1965.000000             100.000000           94.200000

In [20]:
df.describe(include="object")

         university_name institution_type state employment_rate
count                 53               53    53              52
unique                50                2    23              46
top     Williams College          Private    CA            89,1
freq                   2               37    12               2

In [21]:
df["state"].value_counts().head()

state
CA    12
MA     7
NY     4
PA     4
IL     3
Name: count, dtype: int64

In [22]:
df[["university_name", "national_rank", "employment_rate"]].sort_values(by="employment_rate", ascending=False).head(10)

,university_name,national_rank,employment_rate
3,Stanford University,4,"97,8"
0,Massachusetts Institute of Technology (MIT),1,"96,2"
23,California Institute of Technology (Caltech),24,"95,1"
5,Harvard University,6,"95,0"
9,University of Pennsylvania,10,"94,8"
2,Princeton University,3,"94,5"
31,Georgia Institute of Technology (Georgia Tech),32,"94,2"
42,Carnegie Mellon University,43,"93,7"
42,Carnegie Mellon University,43,"93,7"
8,Yale University,9,"93,3"

In [23]:
df.columns

Index(['university_name', 'national_rank', 'founded_year', 'institution_type',
       'state', 'research_impact_score', 'intl_student_ratio',
       'employment_rate'],
      dtype='object')

## 4. Data Quality

### Duplicados

In [24]:
df.duplicated().sum()

np.int64(3)

In [25]:
df[df.duplicated(keep="first")].sort_values(by="university_name")

,university_name,national_rank,founded_year,institution_type,state,research_impact_score,intl_student_ratio,employment_rate
42,Carnegie Mellon University,43,1900,Private,PA,99.0,84.3,"93,7"
43,"University of California, Davis",44,1905,Public,CA,88.7,NaN,"82,5"
6,Williams College,7,1793,Private,MA,45.2,8.5,"89,1"

In [26]:
df.drop_duplicates(keep="first", inplace=True)

### Nulos

In [27]:
df.isnull().sum()

university_name          0
national_rank            0
founded_year             0
institution_type         0
state                    0
research_impact_score    0
intl_student_ratio       5
employment_rate          1
dtype: int64

In [28]:
df[df.isnull().any(axis=1)]

,university_name,national_rank,founded_year,institution_type,state,research_impact_score,intl_student_ratio,employment_rate
12,University of Chicago,13,1890,Private,IL,96.8,NaN,"91,2"
23,California Institute of Technology (Caltech),24,1891,Private,CA,96.8,NaN,"95,1"
29,University of Florida,30,1853,Public,FL,88.4,NaN,"84,1"
33,University of Virginia,34,1819,Public,VA,87.3,14.1,NaN
38,Bowdoin College,39,1794,Private,ME,30.1,NaN,"86,0"
43,"University of California, Davis",44,1905,Public,CA,88.7,NaN,"82,5"

In [29]:
# Eliminar nulos en employment_rate
df.dropna(subset="employment_rate", inplace=True)

In [30]:
# Inputar nulos en int_student_ratio con la mediana (mas robusta a outliers)
df["intl_student_ratio"] = df["intl_student_ratio"].fillna(df["intl_student_ratio"].median())
# df.fillna(subset="intl_student_ratio", inplace=True)

## Transformaciones

In [31]:
# Reemplazar , por . en employment_rate
df["employment_rate"] = df["employment_rate"].str.replace(",", ".", regex=False)
df["employment_rate"] = pd.to_numeric(df["employment_rate"], errors="coerce")

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 0 to 49
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   university_name        49 non-null     object
 1   national_rank          49 non-null     int64
 2   founded_year           49 non-null     int64
 3   institution_type       49 non-null     object
 4   state                  49 non-null     object
 5   research_impact_score  49 non-null     float64
 6   intl_student_ratio     49 non-null     float64
 7   employment_rate        49 non-null     float64
dtypes: float64(3), int64(2), object(3)
memory usage: 3.4+ KB

# 10. Metrica recomendación

Tomamos 
* `national_rank` : The 2026 Forbes ranking position (1-50) 
[ 1 Mayor Importancia - 0 Menor Importancia]
* `employment_rate`: % of graduates employed or in grad school within 1 year.

In [33]:
df["ranking"] = 51 - df["national_rank"]

df["ranking_norm"] = (
    df["ranking"].max() - df["ranking"]
) / (
    df["ranking"].max() - df["ranking"].min()
)

df["employment_norm"] = (
    df["employment_rate"] - df["employment_rate"].min()
) / (
    df["employment_rate"].max() - df["employment_rate"].min()
)
df["recommendation_index"] = (
    0.6 * df["ranking_norm"] +
    0.4 * df["employment_norm"]
)
recommendation = df.sort_values(
    by="recommendation_index",
    ascending=False
).head(5)

recommendation[["university_name", "national_rank", "employment_rate", "recommendation_index"]]

,university_name,national_rank,employment_rate,recommendation_index
42,Carnegie Mellon University,43,93.7,0.811141
46,Washington and Lee University,47,91.5,0.804775
45,University of Texas at Austin,46,89.2,0.734668
47,Colgate University,48,88.1,0.731485
48,New York University (NYU),49,87.4,0.726120